export default {
	SAVE_USER: 'SAVE_USER',
	ADD_EVENT: 'ADD_EVENT',
	GET_EVENTS: 'GET_EVENTS',
	GET_USER_DETAILS: 'GET_USER_DETAILS',
	REQUEST_TO_JOIN: 'REQUEST_TO_JOIN',
	CHAT_ACCESS:'CHAT_ACCESS',
	FILTER_EVENTS:'FILTER_EVENTS',
	EVENTS_RELATED_TO_ME:'EVENTS_RELATED_TO_ME',
	CLEARE_STATE:'CLEARE_STATE'
	

};